exclude: "docs|.git"
default_stages: ["commit"]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: no-commit-to-branch
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args: ["--config=pyproject.toml"]
        additional_dependencies: ["toml"]

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]
        additional_dependencies: ["flake8-isort"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args: ["--config-file=pyproject.toml"]
        additional_dependencies: ["pytest~=6.2.5","toml"]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-no-eval
      - id: python-use-type-annotations

  - repo: local
    hooks:
      - id: pytest-cov
        name: pytest-cov
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true

  # - repo: local
  #   hooks:
  #     - id: pytest-check
  #       name: pytest-check
  #       entry: pytest
  #       language: system
  #       pass_filenames: false
  #       always_run: true
  #     - id: coverage
  #       name: coverage run
  #       language: system
  #       entry: coverage run -m pytest
  #       pass_filenames: false
  #     - id: coverage-html
  #       name: coverage html
  #       language: system
  #       entry: coverage html
  #       pass_filenames: false

  # - repo: https://github.com/regebro/pyroma
  #   rev: "3.2"
  #   hooks:
  #     - id: pyroma


# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false
